import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f8f8',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
        color: '#333',
    },
    questionText: {
        fontSize: 18,
        marginBottom: 20,
        textAlign: 'center',
        color: '#333',
    },
    answerBoxesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 20,
    },
    answerBox: {
        width: 30,
        height: 30,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ccc',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 5,
    },
    answerBoxText: {
        fontSize: 18,
    },
    answerInput: {
        marginBottom: 20,
        borderWidth: 1, 
        borderColor: '#ccc', 
        borderRadius: 5, 
        paddingVertical: 10, 
        paddingHorizontal: 15, 
        width: '100%', 
    },
    button: {
        backgroundColor: '#FF4500',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 25,
        elevation: 3,
        marginBottom: 20, 
    },
    buttonText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#fff',
      textAlign: 'center',
      padding: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#000',
    },
    clueText: {
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
        color: '#555',
    },
    score: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 20,
    },
    timer: {
        fontSize: 18,
        fontWeight: 'bold', 
        marginTop: 10, 
        color: '#333', 
    },
    startButton: {
        backgroundColor: '#FF4500',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 25,
        elevation: 3,
        marginBottom: 20,
        borderBottomWidth: 2, 
        borderBottomColor: '#333', 
      },
    
      startButtonText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
      },
      weltitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 20,
      },
      welbackground: {
        flex: 1,
        resizeMode: 'cover',
        justifyContent: 'center',
    },
    welcontainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
});